name: movieapp
description: A movie search application using TMDb API.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

    # LOCALIZATION
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  # LINT
  very_good_analysis: ^7.0.0

  # FIREBASE
  firebase_core: ^3.10.0
  firebase_analytics: ^11.4.0
  firebase_crashlytics: ^4.3.0

  # NETWORK
  dio: ^5.7.0
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0

  # Navigation
  auto_route: ^9.2.2
  auto_route_generator: ^9.0.0

  # ENVIRONMENT
  envied: ^1.0.1

  # DI
  get_it: ^8.0.3

  # LOGGER
  logger: ^2.5.0

  # JSON SERIALIZATION
  dart_mappable: ^4.3.0

  # ANALYTICS
  sentry_flutter: ^8.12.0

  # HIVE (LOCAL STORAGE)
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider:
    ^2.1.5

    # UI
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flex_color_scheme: ^8.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  retrofit_generator: ^9.1.7

  flutter_lints: ^5.0.0

  envied_generator: ^1.0.1

  # Code Generation
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
